services:
  redis:
    container_name: redis_container
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --loglevel warning --appendonly yes  # Thêm appendonly để đảm bảo persistence
    volumes:
      - redis_data:/data  # Sử dụng named volume thay vì bind mount

  redis-commander:
    container_name: redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
    restart: always
    ports:
      - '8082:8082'
    environment:
      - REDIS_HOSTS=local:redis_container:6379
      - PORT=8082

  mongodb:
    image: mongo
    container_name: mongo_db
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db  # Data directory
      - mongodb_config:/data/configdb  # Config directory
    environment:
      - MONGO_INITDB_ROOT_USERNAME=takeitiz
      - MONGO_INITDB_ROOT_PASSWORD=takeitiz
    restart: always

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=takeitiz
      - ME_CONFIG_MONGODB_ADMINPASSWORD=takeitiz
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_URL=mongodb://takeitiz:takeitiz@mongodb:27017/
      - ME_CONFIG_BASICAUTH_USERNAME=takeitiz
      - ME_CONFIG_BASICAUTH_PASSWORD=takeitiz
    depends_on:
      - mongodb

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"
    volumes:
      - zookeeper_data:/var/lib/zookeeper/data
      - zookeeper_log:/var/lib/zookeeper/log
    networks:
      - microservices-net

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: ms_kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - microservices-net

  mail-dev:
    container_name: ms-mail-dev
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

networks:
  microservices-net:
    driver: bridge

volumes:
  # Định nghĩa các named volumes
  redis_data:
    name: redis_data
  mongodb_data:
    name: mongodb_data
  mongodb_config:
    name: mongodb_config
  zookeeper_data:
    name: zookeeper_data
  zookeeper_log:
    name: zookeeper_log
  kafka_data:
    name: kafka_data
