server:
  port: 4004
spring:
  application:
    name: "gigs"
  config:
    import: "optional:configserver:http://localhost:8071/"
  data:
    mongodb:
      host: localhost
      port: 27017
      database: gigsdb
      username: takeitiz
      password: takeitiz
      authentication-database: admin
      auto-index-creation: true
    redis:
      host: localhost
      port: 6379
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: updateGigCountMessageDto:com.project3.gigs.dto.UpdateGigCountMessageDto
    consumer:
      bootstrap-servers: localhost:9092
      group-id: userGroup, userGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: seedMessageDto:com.project3.gigs.dto.SeedMessageDto,reviewMessageDetailsDto:com.project3.gigs.dto.ReviewMessageDetailsDto

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "gigs"
    description: "Project3 Gigs Application"
    version: "1.0.0"

cloudinary:
  cloud-name: "dwuvvf1tm"
  api-key: "935826224131117"
  api-secret: "k1E47y6AjRzzsyEgCpW0JjmAEX8"


