server:
  port: 8090
spring:
  application:
    name: "gigs"
  config:
    import: "optional:configserver:http://localhost:8071/"
  data:
    mongodb:
      host: localhost
      port: 27017
      database: gigsdb
      username: takeitiz
      password: takeitiz
      authentication-database: admin
      auto-index-creation: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "gigs"
    description: "Project3 Gigs Application"
    version: "1.0.0"

cloudinary:
  cloud-name: "dwuvvf1tm"
  api-key: "935826224131117"
  api-secret: "k1E47y6AjRzzsyEgCpW0JjmAEX8"


