spring:
  application:
    name: "gatewayserver"
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/api/v1/auth/**
        - id: users-buyer
          uri: lb://users
          predicates:
            - Path=/api/v1/buyer/**
        - id: users-seller
          uri: lb://users
          predicates:
            - Path=/api/v1/seller/**
        - id: gig
          uri: lb://gigs
          predicates:
            - Path=/api/v1/gig/**
        - id: chat
          uri: lb://chat
          predicates:
            - Path=/api/v1/message/**
        - id: order
          uri: lb://order
          predicates:
            - Path=/api/v1/order/**
        - id: review
          uri: lb://review
          predicates:
            - Path=/api/v1/review/**
  data:
    redis:
      host: localhost
      port: 6379

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true

info:
  app:
    name: "gatewayserver"
    description: "Gateway Server Application"
    version: "1.0.0"

server:
  port: 4000

socket-server:
  host: localhost
  port: 3999

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: "http://localhost:8070/eureka/"

chat-service:
  socket-url: "http://localhost:4006"

order-service:
  socket-url: "http://localhost:4008"